# Generated by Django 6.0.7 on 2026-07-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('rack_id', models.IntegerField(blank=True, null=True)),
                ('retail_price', models.DecimalField(decimal_places=4, max_digits=6)),
                ('latitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('longitude', models.FloatField(blank=True, db_index=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='routing_fue_latitud_6dc999_idx')],
            },
        ),
    ]
